services:
  - type: web
    name: intelligent-network-assistant
    runtime: python
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt && python model/train_model.py"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        value: 10000
